"""add_fk_produtos_categoria

Revision ID: e8b07745899d
Revises: 001
Create Date: 2026-04-12 19:32:56.538577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8b07745899d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'produtos', 'categoria_imagens', ['categoria_produto'], ['Categoria'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    # ### end Alembic commands ###
